name: arm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4'
    - name: make libraries
      run: make lib
    - name: make
      run: make
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: olearia.bin
        path: build/olearia.bin
